# This file is generated automatically by : python menuconfig.py -s D:\github_examples\photo-album\prj.conf
CONFIG_SUPPORT_ATCMD=n
CONFIG_ATCMD_NETWORK=n
CONFIG_VFS_LITTLEFS_INCLUDED=n
CONFIG_VFS_FATFS_INCLUDED=y
CONFIG_FATFS_DISK_SD_MENU=y
CONFIG_FATFS_SD_HOTPLUG_MENU=y
CONFIG_FATFS_READ_ONLY=y
CONFIG_OTA_SWITCH_STRATEGY=n
CONFIG_CLKCFG_1P0_AUDIO_USB=y
CONFIG_GRAPHIC_UI_MENU=y
CONFIG_LVGL_ENABLE=y
CONFIG_T1720A_MENU=y
CONFIG_TOUCH_ENABLE=y
CONFIG_TOUCH_GT911_MENU=y
CONFIG_LIBJPEG_TURBO_ENABLE=y
CONFIG_WLAN_MENU=n
CONFIG_MBEDTLS_ENABLED_MENU=n
