/*
 * album_photos.h — photo table for the album demo
 *
 * ⚠ AUTO-GENERATED by tools/jpg2album.py — DO NOT EDIT BY HAND.
 *   python tools/jpg2album.py photos_in/
 */

#ifndef ALBUM_PHOTOS_H
#define ALBUM_PHOTOS_H

#include <stdint.h>
#include <stddef.h>   /* NULL — returned by album_photo_at() out of range */

typedef struct
{
    const uint8_t* data; /* JPEG stream (const → .rodata in flash/XIP) */
    uint32_t       len;
    const char*    name; /* display name (file stem) */
} album_photo_t;

/* Implemented in assets/photos/album_photos.c (generated alongside header). */
int                  album_photo_count(void);
const album_photo_t* album_photo_at(int index); /* NULL when out of range */

#endif /* ALBUM_PHOTOS_H */
