#!/usr/bin/env python
"""
gen_launcher_icons.py — generate launcher card icons for photo_album_demo.

Produces two large A8-format icons drawn procedurally (no PNG assets needed):
  icon_camera.c — photo camera (JPG Album card)
  icon_video.c  — video camera (MJPEG Video card)

A8 = LV_COLOR_FORMAT_A8: an 8-bit alpha mask.  LVGL 9.3 tints it with
lv_image_set_recolor()/recolor_opa at draw time, so the .c data is
colourless (white mask), exactly like pc_dashboard_demo's weather icons.

Output (overwritten):
    app_example/assets/icons/icon_camera.c
    app_example/assets/icons/icon_video.c
    app_example/assets/icons/icons.h   (extern decls)
"""

import math
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
PROJ = HERE.parent
OUT_DIR = PROJ / "app_example" / "assets" / "icons"

W = H = 72


def new_canvas():
    """72x72 zero-initialized = fully transparent."""
    return [[0] * W for _ in range(H)]


def set_px(c, x, y, alpha=0xFF):
    """Alpha-additive pixel write (keeps AA falloff)."""
    if 0 <= x < W and 0 <= y < H:
        c[y][x] = max(c[y][x], int(alpha))


def fill_circle(c, cx, cy, r, alpha=0xFF):
    """Filled circle with ~0.5px AA falloff at the edge."""
    for dy in range(-r - 1, r + 2):
        for dx in range(-r - 1, r + 2):
            d = math.hypot(dx, dy)
            if d <= r - 0.5:
                set_px(c, cx + dx, cy + dy, alpha)
            elif d <= r + 0.5:
                fade = int((r + 0.5 - d) * alpha)
                set_px(c, cx + dx, cy + dy, fade)


def fill_rect(c, x0, y0, x1, y1, alpha=0xFF):
    for y in range(max(0, y0), min(H, y1 + 1)):
        for x in range(max(0, x0), min(W, x1 + 1)):
            set_px(c, x, y, alpha)


def clear_px(c, x, y):
    """Make a pixel transparent so details can be cut from a solid shape."""
    if 0 <= x < W and 0 <= y < H:
        c[y][x] = 0


def clear_circle(c, cx, cy, r):
    """Cut a hard-edged transparent circle from the mask."""
    for dy in range(-r, r + 1):
        for dx in range(-r, r + 1):
            if dx * dx + dy * dy <= r * r:
                clear_px(c, cx + dx, cy + dy)


def fill_round_rect(c, x0, y0, x1, y1, radius, alpha=0xFF):
    """Fill a crisp rounded rectangle, inclusive bounds."""
    for y in range(max(0, y0), min(H, y1 + 1)):
        for x in range(max(0, x0), min(W, x1 + 1)):
            cx = x
            cy = y
            if x < x0 + radius:
                cx = x0 + radius
            elif x > x1 - radius:
                cx = x1 - radius
            if y < y0 + radius:
                cy = y0 + radius
            elif y > y1 - radius:
                cy = y1 - radius
            if (x - cx) * (x - cx) + (y - cy) * (y - cy) <= radius * radius:
                set_px(c, x, y, alpha)


def clear_play_triangle(c, left, top, bottom, tip):
    """Cut a right-facing play triangle from a solid body."""
    for y in range(top, bottom + 1):
        half = (tip - left) * abs(y - (top + bottom) / 2) / ((bottom - top) / 2)
        right = int(tip - half)
        for x in range(left, right + 1):
            clear_px(c, x, y)


def stroke_rect(c, x0, y0, x1, y1, alpha=0xFF, thick=2):
    """1px frame, optionally thickened outward by `thick` (drawn as annulus)."""
    for y in range(max(0, y0), min(H, y1 + 1)):
        for x in range(max(0, x0), min(W, x1 + 1)):
            # True only when on the 1px border line
            on_border = (x in range(x0, x1 + 1) and (y == y0 or y == y1)) or \
                        (y in range(y0, y1 + 1) and (x == x0 or x == x1))
            if on_border:
                # thicken: replicate N px outward (simple 4-dir soup)
                for ox in range(-(thick // 2), (thick + 1) // 2):
                    for oy in range(-(thick // 2), (thick + 1) // 2):
                        set_px(c, x + ox, y + oy, alpha)


def draw_line(c, x0, y0, x1, y1, alpha=0xFF):
    """Bresenham line."""
    dx = abs(x1 - x0)
    dy = -abs(y1 - y0)
    sx = 1 if x0 < x1 else -1
    sy = 1 if y0 < y1 else -1
    err = dx + dy
    x, y = x0, y0
    while True:
        set_px(c, x, y, alpha)
        if x == x1 and y == y1:
            break
        e2 = 2 * err
        if e2 >= dy:
            err += dy
            x += sx
        if e2 <= dx:
            err += dx
            y += sy


def to_c_array(canvas):
    """Row-major flat byte array (72*72 = 5184 bytes)."""
    flat = []
    for row in canvas:
        flat.extend(row)
    return bytes(flat)


def write_icon_file(name, bitmap_bytes):
    b = bitmap_bytes
    lines = []
    lines.append('/*')
    lines.append(' * AUTO-GENERATED by tools/gen_launcher_icons.py — DO NOT EDIT.')
    lines.append(' * A8 alpha mask (colourless).  Tint at runtime via')
    lines.append(' * lv_image_set_recolor() (see launcher_ui.c).')
    lines.append(' */')
    lines.append('')
    lines.append('#include "lvgl.h"')
    lines.append('')
    lines.append(f'LV_ATTRIBUTE_LARGE_CONST static const uint8_t {name}_bitmap[] = {{')
    for i in range(0, len(b), 16):
        chunk = b[i:i + 16]
        # Emitted as PLAIN DECIMAL byte values (no "0x", no leading zero):
        #   0 .. 255, e.g. "99" == 0x63.
        # Two reasons:
        #  - an "0xNN" literal in a generated file can get rewritten by the
        #    local toolchain to its decimal value anyway (equal for uint8_t);
        #  - a leading-zero decimal like "000" reads as OCTAL in C, and any
        #    digit 8 or 9 in it is then an illegal octal constant.
        # Plain decimal dodges both.
        hex_str = ', '.join(f'{v}' for v in chunk)
        lines.append(f'    {hex_str},')
    lines.append('};')
    lines.append('')
    lines.append(f'const lv_image_dsc_t {name} = {{')
    lines.append('    .header = {')
    lines.append('        .magic = LV_IMAGE_HEADER_MAGIC,')
    lines.append('        .cf = LV_COLOR_FORMAT_A8,')
    lines.append('        .flags = 0,')
    lines.append('        .w = 72,')
    lines.append('        .h = 72,')
    lines.append('        .stride = 72,')
    lines.append('        .reserved_2 = 0,')
    lines.append('    },')
    lines.append(f'    .data_size = {len(b)},')
    lines.append(f'    .data = {name}_bitmap,')
    lines.append('};')
    lines.append('')
    text = "\n".join(lines)
    # newline="\n": the repo pins *.c/*.h to LF (.gitattributes), and the
    # committed icons are LF — regenerating must reproduce them byte-for-byte.
    (OUT_DIR / f"{name}.c").write_text(text + "\n", encoding="utf-8", newline="\n")
    print(f"  Wrote {name}.c  ({len(b)} bytes)")


def fill_circle_crisp(c, cx, cy, r, alpha=0xFF):
    """Filled circle with a hard edge for small, high-contrast details."""
    for dy in range(-r, r + 1):
        for dx in range(-r, r + 1):
            if dx * dx + dy * dy <= r * r:
                set_px(c, cx + dx, cy + dy, alpha)


def gen_camera():
    """Photo camera: solid silhouette with crisp lens and viewfinder cutouts."""
    c = new_canvas()

    # Use one solid silhouette.  A8 is an alpha mask, so lower-alpha pixels
    # cannot darken an existing fill; transparent cutouts keep the lens sharp.
    fill_round_rect(c, 5, 22, 67, 65, 9)
    fill_round_rect(c, 23, 13, 48, 25, 3)
    fill_round_rect(c, 52, 19, 63, 27, 2)

    # Lens ring and central highlight, both deliberately hard-edged.
    fill_circle_crisp(c, 31, 45, 18)
    clear_circle(c, 31, 45, 12)
    fill_circle_crisp(c, 31, 45, 5)
    clear_circle(c, 31, 45, 1)

    # A simple flash cutout gives the upper-right detail a clean silhouette.
    clear_circle(c, 57, 23, 2)
    return c


def gen_video():
    """Video camera: bold camcorder silhouette with a clear play cutout."""
    c = new_canvas()

    # Main camcorder body and the large right-facing lens hood.
    fill_round_rect(c, 4, 22, 51, 65, 9)
    fill_round_rect(c, 47, 30, 68, 56, 5)

    # Large lens ring.  Cutouts, rather than translucent overlays, preserve
    # contrast in an A8 mask and prevent the icon from looking washed out.
    fill_circle_crisp(c, 20, 44, 17)
    clear_circle(c, 20, 44, 11)
    fill_circle_crisp(c, 20, 44, 5)
    clear_circle(c, 20, 44, 1)

    # Prominent play symbol cut through the body so it reads as video/MJPEG.
    clear_play_triangle(c, 29, 32, 55, 44)

    # Top viewfinder and a compact record marker.
    fill_round_rect(c, 12, 14, 28, 25, 3)
    fill_circle_crisp(c, 44, 27, 4)
    return c



def gen_video_old():
    """Retained design reference; not emitted."""
    c = new_canvas()
    fill_round_rect(c, 8, 23, 50, 59, 7)
    fill_round_rect(c, 45, 30, 64, 52, 4)
    return c


def write_icons_h(names):
    lines = []
    lines.append('/*')
    lines.append(' * icons.h — generated with tools/gen_launcher_icons.py.')
    lines.append(' * A8 alpha-mask icons tinted at runtime by launcher_ui.c.')
    lines.append(' */')
    lines.append('')
    lines.append('#ifndef LAUNCHER_ICONS_H')
    lines.append('#define LAUNCHER_ICONS_H')
    lines.append('')
    lines.append('#include "lvgl.h"')
    lines.append('')
    for n in names:
        lines.append(f'extern const lv_image_dsc_t {n};')
    lines.append('')
    lines.append('#endif /* LAUNCHER_ICONS_H */')
    lines.append('')
    (OUT_DIR / "icons.h").write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"  Wrote icons.h  ({len(names)} icons)")


if __name__ == '__main__':
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    canvas_camera = gen_camera()
    write_icon_file("icon_camera", to_c_array(canvas_camera))
    canvas_video = gen_video()
    write_icon_file("icon_video", to_c_array(canvas_video))

    write_icons_h(["icon_camera", "icon_video"])

    print("\nDone! 2 launcher icons generated in app_example/assets/icons/")
