#!/usr/bin/env python
"""
jpg2album.py — embed JPEG files into flash as C arrays for photo_album_demo.

The RTL8721F HW JPEG decoder consumes the raw JPEG stream directly, so the
images are embedded byte-for-byte (no pixel conversion).  Optional --max-kb
re-encodes via Pillow to keep total flash usage under control.

Usage:
    python tools/jpg2album.py photos_in/
    python tools/jpg2album.py a.jpg b.jpg ...
    python tools/jpg2album.py photos_in/ --max-kb 64 -q 80
    python tools/jpg2album.py photos_in/ --reencode   # normalise every photo

Output (overwritten):
    app_example/assets/photos/album_photos.h   (types + API decls)
    app_example/assets/photos/album_photos.c   (JPEG arrays + table)

Flash budget note: arrays are const → .rodata in XIP flash.  Image2 flash
region is limited; keep the total well below it (the script prints the sum).
"""

import argparse
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
PROJ = HERE.parent
OUT_H = PROJ / "app_example" / "assets" / "photos" / "album_photos.h"
OUT_C = PROJ / "app_example" / "assets" / "photos" / "album_photos.c"

JPEG_EXTS = {".jpg", ".jpeg"}


def collect_images(inputs):
    """Expand dirs/globs into a sorted, de-duplicated list of JPEG paths."""
    paths = []
    for item in inputs:
        p = pathlib.Path(item)
        if p.is_dir():
            paths.extend(f for f in sorted(p.iterdir()) if f.suffix.lower() in JPEG_EXTS)
        elif p.is_file():
            paths.append(p)
        else:
            print(f"warning: skip (not found): {item}", file=sys.stderr)
    # de-dupe, keep order
    seen, uniq = set(), []
    for p in paths:
        r = p.resolve()
        if r not in seen:
            seen.add(r)
            uniq.append(p)
    return uniq


def maybe_compress(path, max_kb, quality):
    """Return JPEG bytes; re-encode if file exceeds max_kb (Pillow)."""
    data = path.read_bytes()
    if max_kb is None or len(data) <= max_kb * 1024:
        return data
    return reencode_jpeg(path, quality)


def reencode_jpeg(path, quality):
    """Force-reencode via Pillow into a STANDARD baseline JPEG (see below).

    The RTL8721F HX170 decoder + PP pipeline is only validated for the plain
    baseline 4:2:2 form (Y H2V1 + Cb/Cr H1V1, NV12 semi-planar output, no
    EXIF / APP14 / 31-181-style Huffman tables).  Files that hit those edge
    forms have shown washed-out / colour-inverted photos (chroma-plane
    mis-read) under PP scaling, even with jpeg_pp_in_fmt() mapping the
    decoder-reported format correctly.  Re-encoding here normalises every
    photo to a form the HW path is known to handle.
    """
    try:
        from PIL import Image
        import io
    except ImportError:
        print(f"warning: {path.name} re-encode requested "
              f"but Pillow not installed — embedding as-is", file=sys.stderr)
        return path.read_bytes()

    # subsampling=1 → 4:2:2 (H2V1).  The HW JPEG+PP path handles 4:2:2 and
    # 4:2:0 both correctly (jpeg_pp_in_fmt() maps whatever the decoder
    # reports); this flag is about normalising to ONE known-good standard
    # form, not about 4:2:0.  optimize=True gives Pillow's COMPACT Huffman
    # tables (29/89/25/36-style, like the known-good landscape photo) instead
    # of the default 31/181 DC/AC form.  progressive=False forces a baseline
    # SOF0 stream.
    img.save(buf, format="JPEG", quality=quality, subsampling=1,
             optimize=True, progressive=False, exif=b"")
    out = buf.getvalue()

    orig = path.read_bytes()
    print(f"  re-encoded {path.name}: {len(orig)//1024} KB -> {len(out)//1024} KB "
          f"(standard baseline 4:2:2)")
    return out


def c_ident(stem, idx):
    """Sanitize a file stem into a C identifier fragment."""
    frag = re.sub(r"[^0-9a-zA-Z_]", "_", stem)
    if not frag or frag[0].isdigit():
        frag = f"p{idx}_{frag}"
    return frag


def emit(out_h, out_c, photos):
    """photos: list of (name, ident, bytes)."""
    hdr = """/*
 * album_photos.h — photo table for the album demo
 *
 * ⚠ AUTO-GENERATED by tools/jpg2album.py — DO NOT EDIT BY HAND.
 *   python tools/jpg2album.py photos_in/
 */

#ifndef ALBUM_PHOTOS_H
#define ALBUM_PHOTOS_H

#include <stdint.h>
#include <stddef.h>   /* NULL — returned by album_photo_at() out of range */

typedef struct
{
    const uint8_t* data; /* JPEG stream (const → .rodata in flash/XIP) */
    uint32_t       len;
    const char*    name; /* display name (file stem) */
} album_photo_t;

/* Implemented in assets/photos/album_photos.c (generated alongside header). */
int                  album_photo_count(void);
const album_photo_t* album_photo_at(int index); /* NULL when out of range */

#endif /* ALBUM_PHOTOS_H */
"""
    # newline="\n": the repo pins *.c/*.h to LF (.gitattributes, core.autocrlf
    # is irrelevant for generated files written straight into the worktree).
    out_h.write_text(hdr, encoding="utf-8", newline="\n")

    lines = [
        "/*",
        " * album_photos.c — photo table (JPEG byte arrays, flash/XIP).",
        " *",
        " * ⚠ AUTO-GENERATED by tools/jpg2album.py — DO NOT EDIT BY HAND.",
        " */",
        "",
        '#include "assets/photos/album_photos.h"',
        "",
    ]

    total = 0
    for name, ident, data in photos:
        total += len(data)
        lines.append(f"/* {name} — {len(data)} bytes */")
        lines.append(f"static const uint8_t album_img_{ident}[] = {{")
        row = []
        for i, b in enumerate(data):
            row.append(f"0x{b:02x},")
            if len(row) == 16:
                lines.append("    " + "".join(row))
                row = []
        if row:
            lines.append("    " + "".join(row))
        lines.append("};")
        lines.append("")

    lines.append("static const album_photo_t s_photos[] = {")
    for name, ident, data in photos:
        lines.append(f'    {{ album_img_{ident}, {len(data)}, "{name}" }},')
    lines.append("};")
    lines.append("")
    lines.append("#define ALBUM_PHOTO_COUNT ((int) (sizeof(s_photos) / sizeof(s_photos[0])))")
    lines.append("")
    lines.append("""
int album_photo_count(void)
{
    return ALBUM_PHOTO_COUNT;
}

const album_photo_t* album_photo_at(int index)
{
    if (index < 0 || index >= ALBUM_PHOTO_COUNT)
        return NULL;
    return &s_photos[index];
}
""".lstrip("\n"))

    out_c.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return total


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", nargs="+", help="JPEG files and/or directories")
    ap.add_argument("--max-kb", type=int, default=None,
                    help="re-encode images larger than N KB (needs Pillow)")
    ap.add_argument("-q", "--quality", type=int, default=80,
                    help="JPEG quality for --max-kb re-encoding (default 80)")
    ap.add_argument("--reencode", dest="reencode", action="store_true",
                    help="RE-ENCODE every image via Pillow to a standard baseline "
                         "JPEG (no EXIF/APP14, compact Huffman tables, 4:2:2 "
                         "chroma — the form the HW JPEG+PP path is validated for).  "
                         "Use when a photo shows washed-out/inverted colours from "
                         "the HW JPEG+PP path under scaling.")
    args = ap.parse_args()

    paths = collect_images(args.inputs)
    if not paths:
        print("no JPEG files found", file=sys.stderr)
        return 1

    photos = []
    used_idents = set()
    for idx, p in enumerate(paths):
        if args.reencode:
            data = reencode_jpeg(p, args.quality)
        else:
            data = maybe_compress(p, args.max_kb, args.quality)
        if not (data[:2] == b"\xff\xd8"):
            print(f"warning: {p.name} is not a JPEG (missing SOI) — skipped", file=sys.stderr)
            continue
        ident = c_ident(p.stem, idx)
        while ident in used_idents:
            ident += "_"
        used_idents.add(ident)
        photos.append((p.stem, ident, data))

    if not photos:
        print("no valid JPEG images", file=sys.stderr)
        return 1

    total = emit(OUT_H, OUT_C, photos)
    print(f"generated {len(photos)} photos, total {total} bytes ({total/1024:.1f} KB)")
    print(f"  -> {OUT_H}")
    print(f"  -> {OUT_C}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
